name: ci

on:
  push:
    branches:
      - dev
  pull_request:
    types: [closed]
  release:
    types: [published]

jobs:
  docker_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout expex master breanch
        uses: actions/checkout@v2
        if: ${{ github.event_name == 'release' || github.event.pull_request.merged == true }}
        with:
          repository: xec-cm/expex
          ref: master
          path: expex

      - name: Checkout expex dev breanch
        uses: actions/checkout@v2
        if: ${{ github.event_name == 'push' }}
        with:
          repository: xec-cm/expex
          ref: dev
          path: expex

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push dev breanch
        uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'push' }}
        with:
          context: .
          file: ./expex/Dockerfile
          platforms: linux/386, linux/amd64
          push: true
          no-cache: true
          tags: |
            francesccatala/expex:dev

      - name: Build and push main breanch
        uses: docker/build-push-action@v2
        if: ${{ github.event.pull_request.merged == true }}
        with:
          context: .
          file: ./expex/Dockerfile
          platforms: linux/386, linux/amd64
          push: true
          no-cache: true
          tags: |
            francesccatala/expex:main

      - name: Build and push release
        uses: docker/build-push-action@v2
        if: ${{ github.event_name == 'release' }}
        with:
          context: .
          file: ./expex/Dockerfile
          platforms: linux/386, linux/amd64
          push: true
          no-cache: true
          tags: |
            francesccatala/expex:latest
